#define db_id_t ui64
#define db_type_id_t ui16
#define db_ordinal_t ui32
#define db_id_mask UINT64_MAX
#define db_type_id_mask UINT16_MAX
#define db_data_len_t ui32
#define db_name_len_t ui8
#define db_name_len_max UINT8_MAX
#define db_data_len_max UINT32_MAX
#define db_fields_len_t ui8
#define db_indices_len_t ui8
#define db_count_t ui32
