#!/bin/sh -e

# description
# * compiles the sc source code to c
# dependencies
# * sph-sc
# * clang-format

name=sph-db
root="$PWD"
sc=src/sc
c=src/c-precompiled

compile_sc() {
  mkdir -p "$c" &&
  cd "$sc" &&
  find -type f -name "*.sc" | sc --stdin-input-paths --parents "$root/$c"
  cd "$root" &&
  find "$c" -type f -exec ./exe/format-c -i '{}' \; &&
  for path in "$c/$name"/*.h.c
  do
    mv "$path" "$(dirname $path)/$(basename $path .h.c).h"
  done
}

compile_sc
