#!/bin/sh
# list all bindings from sph-db.h.
# depends on sc-documentor from sph-sc.

config="$PWD/other/sc-documentor-config.scm"
export SC_LOAD_PATH="$PWD/source/sc"
sc-documentor source/sc/main/sph-db.sc --config="$config" --md-level=2
