#!/bin/sh

# usage: ./exe/install [path-prefix]

prefix="$1"
a="temp/libsph-db.so"
b="source/c-precompiled/sph-db.c"
a_dest="$prefix/usr/lib"
b_dest="$prefix/usr/include"

mkdir -p "$a_dest" "$b_dest" &&
cp -t "$a_dest" "$a" &&
cp -t "$b_dest" $b &&
chmod 644 "$a_dest/libsph-db.so" "$b_dest/sph-db.c"
