#!/usr/bin/guile
!#

; offers more installation options.
; depends on "sph-lib".
; see "./exe/install-extended --help"
(import (sph install))

(install-cli-guile ("/usr/lib" 493 "temp/libsph-db.so")
  ("/usr/include" 493 "source/c-precompiled/main/sph-db.h"))
