#!/bin/sh

# run tests and check for memory leaks with valgrind

#--suppressions=other/valgrind-test/custom.supp

options="--leak-check=yes --leak-check=full --show-leak-kinds=all"
valgrind --tool=memcheck $options ./exe/test $@
